server:
  port: 8009

spring:


#   微服务
  cloud:
#    注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          #          default: #默认
          cloud-payment-service: #可以指定服务进行超时配置
            #连接超时时间
            connectTimeout: 3000
            #读取超时时间
            readTimeout: 3000
      httpclient:
        hc5:
          enabled: true

# Mybatis log plugin 插件输出日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl