server:
  port: 8001

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url:
          username:
          password:
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave:
          url:
          username:
          password:
          driver-class-name:
    druid:
      max-active: 60
      min-idle: 20

#   微服务
  cloud:
#    注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

# Mybatis log plugin 插件输出日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl